[package]
name = "dna_analisys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotpy = "0.5.1"
multiref = "0.1"
postgres = "0.19.7"
serde_json = "1.0.112"
